/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppCashflowRouteImport } from './routes/app.cashflow'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppCombustibleRouteImport } from './routes/app.combustible'
import { Route as AppComprasRouteImport } from './routes/app.compras'
import { Route as AppCreditosRouteImport } from './routes/app.creditos'
import { Route as AppCuentasRouteImport } from './routes/app.cuentas'
import { Route as AppEmpleadosRouteImport } from './routes/app.empleados'
import { Route as AppFacturasRouteImport } from './routes/app.facturas'
import { Route as AppImagenesRouteImport } from './routes/app.imagenes'
import { Route as AppImpuestosRouteImport } from './routes/app.impuestos'
import { Route as AppMediosRouteImport } from './routes/app.medios'
import { Route as AppOcrRouteImport } from './routes/app.ocr'
import { Route as AppPresupuestosRouteImport } from './routes/app.presupuestos'
import { Route as AppProveedoresRouteImport } from './routes/app.proveedores'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as ApiPublicOcrFacturaRouteImport } from './routes/api/public/ocr-factura'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppCashflowRoute = AppCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCombustibleRoute = AppCombustibleRouteImport.update({
  id: '/combustible',
  path: '/combustible',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditosRoute = AppCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AppRoute,
} as any)
const AppCuentasRoute = AppCuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadosRoute = AppEmpleadosRouteImport.update({
  id: '/empleados',
  path: '/empleados',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturasRoute = AppFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AppRoute,
} as any)
const AppImagenesRoute = AppImagenesRouteImport.update({
  id: '/imagenes',
  path: '/imagenes',
  getParentRoute: () => AppRoute,
} as any)
const AppImpuestosRoute = AppImpuestosRouteImport.update({
  id: '/impuestos',
  path: '/impuestos',
  getParentRoute: () => AppRoute,
} as any)
const AppMediosRoute = AppMediosRouteImport.update({
  id: '/medios',
  path: '/medios',
  getParentRoute: () => AppRoute,
} as any)
const AppOcrRoute = AppOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => AppRoute,
} as any)
const AppPresupuestosRoute = AppPresupuestosRouteImport.update({
  id: '/presupuestos',
  path: '/presupuestos',
  getParentRoute: () => AppRoute,
} as any)
const AppProveedoresRoute = AppProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicOcrFacturaRoute = ApiPublicOcrFacturaRouteImport.update({
  id: '/api/public/ocr-factura',
  path: '/api/public/ocr-factura',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/cashflow': typeof AppCashflowRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/combustible': typeof AppCombustibleRoute
  '/app/compras': typeof AppComprasRoute
  '/app/creditos': typeof AppCreditosRoute
  '/app/cuentas': typeof AppCuentasRoute
  '/app/empleados': typeof AppEmpleadosRoute
  '/app/facturas': typeof AppFacturasRoute
  '/app/imagenes': typeof AppImagenesRoute
  '/app/impuestos': typeof AppImpuestosRoute
  '/app/medios': typeof AppMediosRoute
  '/app/ocr': typeof AppOcrRoute
  '/app/presupuestos': typeof AppPresupuestosRoute
  '/app/proveedores': typeof AppProveedoresRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/api/public/ocr-factura': typeof ApiPublicOcrFacturaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/cashflow': typeof AppCashflowRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/combustible': typeof AppCombustibleRoute
  '/app/compras': typeof AppComprasRoute
  '/app/creditos': typeof AppCreditosRoute
  '/app/cuentas': typeof AppCuentasRoute
  '/app/empleados': typeof AppEmpleadosRoute
  '/app/facturas': typeof AppFacturasRoute
  '/app/imagenes': typeof AppImagenesRoute
  '/app/impuestos': typeof AppImpuestosRoute
  '/app/medios': typeof AppMediosRoute
  '/app/ocr': typeof AppOcrRoute
  '/app/presupuestos': typeof AppPresupuestosRoute
  '/app/proveedores': typeof AppProveedoresRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app': typeof AppIndexRoute
  '/api/public/ocr-factura': typeof ApiPublicOcrFacturaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/cashflow': typeof AppCashflowRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/combustible': typeof AppCombustibleRoute
  '/app/compras': typeof AppComprasRoute
  '/app/creditos': typeof AppCreditosRoute
  '/app/cuentas': typeof AppCuentasRoute
  '/app/empleados': typeof AppEmpleadosRoute
  '/app/facturas': typeof AppFacturasRoute
  '/app/imagenes': typeof AppImagenesRoute
  '/app/impuestos': typeof AppImpuestosRoute
  '/app/medios': typeof AppMediosRoute
  '/app/ocr': typeof AppOcrRoute
  '/app/presupuestos': typeof AppPresupuestosRoute
  '/app/proveedores': typeof AppProveedoresRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/api/public/ocr-factura': typeof ApiPublicOcrFacturaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/app/auditoria'
    | '/app/cashflow'
    | '/app/clientes'
    | '/app/combustible'
    | '/app/compras'
    | '/app/creditos'
    | '/app/cuentas'
    | '/app/empleados'
    | '/app/facturas'
    | '/app/imagenes'
    | '/app/impuestos'
    | '/app/medios'
    | '/app/ocr'
    | '/app/presupuestos'
    | '/app/proveedores'
    | '/app/usuarios'
    | '/app/'
    | '/api/public/ocr-factura'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/auditoria'
    | '/app/cashflow'
    | '/app/clientes'
    | '/app/combustible'
    | '/app/compras'
    | '/app/creditos'
    | '/app/cuentas'
    | '/app/empleados'
    | '/app/facturas'
    | '/app/imagenes'
    | '/app/impuestos'
    | '/app/medios'
    | '/app/ocr'
    | '/app/presupuestos'
    | '/app/proveedores'
    | '/app/usuarios'
    | '/app'
    | '/api/public/ocr-factura'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/app/auditoria'
    | '/app/cashflow'
    | '/app/clientes'
    | '/app/combustible'
    | '/app/compras'
    | '/app/creditos'
    | '/app/cuentas'
    | '/app/empleados'
    | '/app/facturas'
    | '/app/imagenes'
    | '/app/impuestos'
    | '/app/medios'
    | '/app/ocr'
    | '/app/presupuestos'
    | '/app/proveedores'
    | '/app/usuarios'
    | '/app/'
    | '/api/public/ocr-factura'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicOcrFacturaRoute: typeof ApiPublicOcrFacturaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cashflow': {
      id: '/app/cashflow'
      path: '/cashflow'
      fullPath: '/app/cashflow'
      preLoaderRoute: typeof AppCashflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/combustible': {
      id: '/app/combustible'
      path: '/combustible'
      fullPath: '/app/combustible'
      preLoaderRoute: typeof AppCombustibleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compras': {
      id: '/app/compras'
      path: '/compras'
      fullPath: '/app/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/creditos': {
      id: '/app/creditos'
      path: '/creditos'
      fullPath: '/app/creditos'
      preLoaderRoute: typeof AppCreditosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cuentas': {
      id: '/app/cuentas'
      path: '/cuentas'
      fullPath: '/app/cuentas'
      preLoaderRoute: typeof AppCuentasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empleados': {
      id: '/app/empleados'
      path: '/empleados'
      fullPath: '/app/empleados'
      preLoaderRoute: typeof AppEmpleadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/facturas': {
      id: '/app/facturas'
      path: '/facturas'
      fullPath: '/app/facturas'
      preLoaderRoute: typeof AppFacturasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imagenes': {
      id: '/app/imagenes'
      path: '/imagenes'
      fullPath: '/app/imagenes'
      preLoaderRoute: typeof AppImagenesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/impuestos': {
      id: '/app/impuestos'
      path: '/impuestos'
      fullPath: '/app/impuestos'
      preLoaderRoute: typeof AppImpuestosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medios': {
      id: '/app/medios'
      path: '/medios'
      fullPath: '/app/medios'
      preLoaderRoute: typeof AppMediosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ocr': {
      id: '/app/ocr'
      path: '/ocr'
      fullPath: '/app/ocr'
      preLoaderRoute: typeof AppOcrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/presupuestos': {
      id: '/app/presupuestos'
      path: '/presupuestos'
      fullPath: '/app/presupuestos'
      preLoaderRoute: typeof AppPresupuestosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proveedores': {
      id: '/app/proveedores'
      path: '/proveedores'
      fullPath: '/app/proveedores'
      preLoaderRoute: typeof AppProveedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/ocr-factura': {
      id: '/api/public/ocr-factura'
      path: '/api/public/ocr-factura'
      fullPath: '/api/public/ocr-factura'
      preLoaderRoute: typeof ApiPublicOcrFacturaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCashflowRoute: typeof AppCashflowRoute
  AppClientesRoute: typeof AppClientesRoute
  AppCombustibleRoute: typeof AppCombustibleRoute
  AppComprasRoute: typeof AppComprasRoute
  AppCreditosRoute: typeof AppCreditosRoute
  AppCuentasRoute: typeof AppCuentasRoute
  AppEmpleadosRoute: typeof AppEmpleadosRoute
  AppFacturasRoute: typeof AppFacturasRoute
  AppImagenesRoute: typeof AppImagenesRoute
  AppImpuestosRoute: typeof AppImpuestosRoute
  AppMediosRoute: typeof AppMediosRoute
  AppOcrRoute: typeof AppOcrRoute
  AppPresupuestosRoute: typeof AppPresupuestosRoute
  AppProveedoresRoute: typeof AppProveedoresRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCashflowRoute: AppCashflowRoute,
  AppClientesRoute: AppClientesRoute,
  AppCombustibleRoute: AppCombustibleRoute,
  AppComprasRoute: AppComprasRoute,
  AppCreditosRoute: AppCreditosRoute,
  AppCuentasRoute: AppCuentasRoute,
  AppEmpleadosRoute: AppEmpleadosRoute,
  AppFacturasRoute: AppFacturasRoute,
  AppImagenesRoute: AppImagenesRoute,
  AppImpuestosRoute: AppImpuestosRoute,
  AppMediosRoute: AppMediosRoute,
  AppOcrRoute: AppOcrRoute,
  AppPresupuestosRoute: AppPresupuestosRoute,
  AppProveedoresRoute: AppProveedoresRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicOcrFacturaRoute: ApiPublicOcrFacturaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
